import = ["~/.config/alacritty/nightfox.toml"]

[window]
dimensions = { columns = 90, lines = 40 }
opacity = 0.95

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 12

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [{ key = "F11", mods = "None", action = "ToggleFullScreen" }]
